# styling
set -g status-style "bg=default"
set -g status-left "#[bold] #S #[nobold]| "
set -g window-status-current-format "#[bold,underscore]#I:#W"
set -g window-status-format "#I:#W"
set -g message-style "bg=default"

set -g status-position top
set -g status-left-length 100

# start session numbering at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# will move window numbers when closing -> remove the gaps
set -g renumber-windows on

# 2000 is a bit too low
set-option -g history-limit 5000

# resize windows with mouse
set -g mouse on

# ofc use vi bindings when possible :)
setw -g mode-keys vi

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

# bindings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# switch windows with ctrl + left/right
bind -n S-Right next-window
bind -n S-Left previous-window

# easily swap windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Allow tmux to set the terminal title
set -g set-titles on
set -g set-titles-string 'tmux: #{session_name} | #{pane_current_command}'
